### ISSUE TITLE
Saber Analysis for Object Fields

### ISSUE THREAD

**Issue by CXWorks** [SVF-tools/SVF#1214]
Hi,

Thanks for your time & patience. 

I'm trying to use SrcSinkDDA to build my own analysis. The problem is I want it to handle the pointers as fields inside an object, which is freed in the later program. The sink point is clear, but I found if I set the src point to the object's base pointer, it can't propergate the analysis through `Load`(it loads the field pointer and then free it). 

I also take a look at the `MemObj` as mentioned in previous issues, but I can't find field information. I wonder how can I enumerate all the fields inside an object as srcs or do you have other comments/suggections on this problem?

Thanks

**Comment by jumormt** [comment]
Hi @CXWorks 

I didn't fully understand your question. Is it possible for you to provide a motivating example?

**Comment by jumormt** [comment]
That's a good question. The slice is not built because your source (`obj`) and sink (e.g., `obj->istore`) are not aliased (unreachable in SVFG). This is because Saber is a field-sensitive analysis that considers each field independently. You need to set the source to the corresponding fields of interest rather than the base object.

**Comment by CXWorks** [comment]
Thanks for clarification!
