### ISSUE TITLE
Imprecise analysis results

### ISSUE THREAD

**Issue by MuhammadAbuBakar95** [SVF-tools/SVF#132]
Hi,

Thanks a lot for providing such a useful tool. 
I am trying to generate a fine-grained call graph for a (large) kernel. For this problem, I am using SVF to generate points-to sets for pointer operands of indirect call Instructions.  I have used the Diff wave propagation inclusion-based analysis.
After going through the results, one issue that I see is that for 900 of these call sites, the target set is exactly the same and contains more than 6500 functions (which is one third of the total number of functions in my IR). Most of these functions seem completely unrelated to the call sites. 

Can you help me in figuring out what is going on?
Is it possible that you guys are using a conservative approach (e.g. signature matching) to overestimate the points-to set that is leading to this result?

Thanks.

**Comment by mbarbar** [comment]
I gather this is a C, not C++, kernel so the only callsites that need resolving would be function pointer calls, and not virtual dispatch. I don't believe SVF ever falls back to signature matching, but @yuleisui can confirm that.

Here are some ideas that might lead to the issue:

1. Try tracing a few of these pointers backwards and see if they share some common source or assignment. It could be one pointer tainting others.

2. If these huge calls are being made from dereferencing memory objects (not a user-defined pointer)\*, and these objects are sourced by a pool allocator\*\* then the imprecision is expected. All concrete objects originating from a single pool will be represented by a single abstract object. In fact, if the objects come from any wrapper function\*\*\* (though I assume you won't be using C's malloc in a kernel), then they are all going to be merged into one abstract object because the anlysis is context-insensitive. It could also be that some single object which has a lot of function targets in its points-to set is "infecting" a lot of pointers similar to the 1st point.

\* e.g. `pt(p) = { o }`, and `void (*fp)(void) = *p; fp();`

** e.g.
```
    char *pool;  // initialise it somewhere.
    void *palloc(size_t s) {
        // find a suitable n...
        return pool[n];
    }
```

*** e.g.
```
    void *xmalloc(size_t s) {
        void *v = malloc(s);
        // do some stuff.
        return v;
    }
```

3. I'm not sure if it could be an array-sensitivity issue because I'm not sure if the analysis is array-sensitive (@yuleisui). If not, then an array of function pointers -> all function pointers in that array share a points-to set.

4. Which options did you run the analysis with? Did you keep field-sensitivity?

5. You mention that most of the functions seem completely unrelated to the callsites. Are these functions ever address-taken? If they aren't it sounds like the analysis is buggy.

Not quite sure what else there is to try, but ultimately I think it would come down to either point 1 or 2 (unless there is a bug). The "shape" of the program really affects the results. If the problem is the shape of the code being unsuitable for Andersen's then the algorithm is the problem. I think there's not much that can be done systematically except using a better analysis which might be too expensive for something as large as a kernel.  Knowing the shape of the problematic code can help in thinking of ways to improve the *algorithm*, but that's a very long process haha.  A bit dodgily, you might be able to exclude problematic objects and stop them from infecting others if you can manually verify they should not be in the points-to set of specific pointers.

By the way, how many callsites are there in total, and how large is the bitcode file?

**Comment by MuhammadAbuBakar95** [comment]
Hi,
Thanks for the detailed response and the useful suggestions.

For now I am focusing on solving the above problem on an application level program before moving back to the kernel.

The program that I have chosen is reasonably complicated. It has around 1100 functions and more than 34000 call sites.

I ran the program bitcode with the "wpa --ander" option. 231 of the callsites return problematic results i.e. their target sets are unimaginably large. Notice that all of these callsites have exactly the same target set for their pointer operands. This target set comprises of 1289 Nodes. One of these nodes is a dummy node. The rest of the nodes correspond to functions, global variables, alloca Instructions, results of malloc calls, mmap calls, dlopen calls etc.

This makes me think that SVF cannot reason confidently about the source pointers of these call Instructions and the sinks of the values in the target set so it conservatively marks all these values as valid points-to targets for the call Instruction operands.

Do you think there is something like that going on?

Answering your questions:

1. The target set for these callsites contain not only functions but also global variables, alloca Instructions, results of malloc calls, mmap calls, dlopen calls etc. so its hard to see any way in which these pointers may be related. 

2. Hmm. I don't think I see your point there. This will be true for the kernel but I think SVF has explicit handling for malloc, so it shouldn't be a problem in application level programs that use malloc. e.g. I tested out the following code:
```
typedef void (*two_args) (char *, char *);
two_args * fh_array; 

void initialize_array() {
	fh_array = malloc(sizeof(two_args) * 4);
	fh_array[0] = &handle_zero; // The target functions.
	fh_array[1] = &handle_one;
	fh_array[2] = &handle_two;
	fh_array[3] = &handle_three;		
}

int main(int argc, char ** argv) {
	initialize_array();
	int idx = atoi(argv[1]);
	fh_array[idx](argv[2], argv[3]);
	return 0;
}
```
The call Instruction at the second last line of main has a target set of the 4 functions whose addresses are stored in fh_array.

3. I think that won't be a problem. As you can see in the example above, all functions in the array will actually be valid targets.

4. I used wpa with --ander option.

5. All the included functions are address taken but as I said in point 1 above, the target set also includes a dummy node, global variables, alloca instructions, results of mallocs, dlopen, mmap etc.

Thanks a lot for helping. I really appreciate it.

**Comment by MuhammadAbuBakar95** [comment]
Just a little FYI. 

One of the call instructions that is problematic is at line 7 in the following code:
```
ngx_int_t
ngx_init_modules(ngx_cycle_t *cycle)
{
    ngx_uint_t  i;
    for (i = 0; cycle->modules[i]; i++) {
        if (cycle->modules[i]->init_module) {
            if (cycle->modules[i]->init_module(cycle) != NGX_OK) {
                return NGX_ERROR;
            }
        }
    }
    return NGX_OK;
}
```
Here cycle and cycle->modules are allocated using a tree of allocation utilities (ngx_pc_alloc calls ngx_palloc which calls ngx_palloc_large which calls ngx_alloc which calls malloc).

cycle->modules is initialized using a global variable ngx_modules which is pre-initialized at compile time.

**Comment by mbarbar** [comment]
>This target set comprises of 1289 Nodes. One of these nodes is a dummy node. The rest of the nodes correspond to functions, global variables, alloca Instructions, results of malloc calls, mmap calls, dlopen calls etc.

This point combined with your example is very important, and it seems like to me the problem is: context-insensitive Andersen's analysis simply cannot handle allocation wrappers (like the allocation you mentioned which makes the `malloc` call). SVF does explicitly handle `malloc`, but it becomes very imprecise when `malloc` is called through an intermediary.

Here's a simpler example:
```
struct A {
    int *i;
};

struct B {
    float *f;
};

// an allocation wrapper, extremely similar to ngx_alloc.
void *xmalloc(size_t s) {
    void *v = malloc(s);  // produces object o.
    assert(v && "allocation failure!");
    return v;
}

int main(void) {
    int local_i;  // say object oi.
    float local_f;  // say object of.

    struct A *a = xmalloc(sizeof(struct A));
    struct B *b = xmalloc(sizeof(struct B));
    // So pt(a) = pt(b) = { o }

    a->i = &local_i;  // i.e. (*a).i = ...
    b->f = &local_f;
}
```

The final result of this code is unfortunate:
1. We have `pt(a) = pt(b) = { o }` despite the fact that `malloc` is clearly called twice, but standard context-**in**sensitive Andersen's won't realise this (we create **one** abstract object per allocation site).

2. For the first field of `o` (call it `o.0` because we work on field indices), we have `pt(o.0) = { oi, of }` because in the last two assignments (through `a` and `b`), we are accessing the same object: `o`.

This is the problem with context-insensitivet pointer analysis and wrappers.

Some solutions:
1. Use a context-sensitive analysis (not available in SVF). For each calling context, essentially, it will reanalyse the function, and so it will produce two separate objects for `a` and `b`. This, to my understanding, gets expensive (consider how deep that allocation wrapper you mentioned is!), and unfortunately not available in SVF.

2. Use a technique which can handle allocation wrappers *better*, like this paper: https://yanniss.github.io/cclyzer-sas16.pdf They have an implementation (https://github.com/plast-lab/cclyzer) but I have never tried it and unsure if there are plans to work on it further. SVF has an implementation under `andertype` but its implemented differently to the paper and not as well tested as the other pointer analyses in SVF. I also recommend taking a look at the paper. If you don't have time, see the second paragraph on page 6 (under point 3) at least for a summary of the problem I am talking about.

3. You could maybe hard code in SVF that the wrapper returns a brand new fresh object (like `malloc`), but this means you need to manually know all the wrappers (not that difficult if your focus is on one project you are familiar with). I'm not sure how easy this is though, and don't really have time to take too deep a look for the next 3 weeks at least.

**Comment by MuhammadAbuBakar95** [comment]
Thanks for the explanation and the useful suggestions.  I can now understand the problem. 
I think I may have to look for a hacky solution.

One last thing. WPA does provide a "-fspta" option for flow-sensitive analysis. Is it not complete yet. Can you share some documentation related to it? 
Thanks a lot.

**Comment by mbarbar** [comment]
You're welcome!

`-fspta` is good to go. Documentation-wise... there's not much except some internals documentation here: https://github.com/SVF-tools/SVF/wiki/Technical-documentation under value-flow construction, and very basic usage documentation here: https://github.com/SVF-tools/SVF/wiki/User-Guide and https://github.com/SVF-tools/SVF/wiki/Analyze-a-Simple-C-Program

Is there anything in particular you're having trouble with?

**Comment by MuhammadAbuBakar95** [comment]
Actually, you said that SVF does not have support for flow sensitive analysis so I thought "fspta" has some different purpose.

Anyway, thanks for all the help. I think we can close this issue.

**Comment by mbarbar** [comment]
Flow-sensitive points-to analysis is available, but it's still context-insensitive. It will be more precise but cannot solve the above problem fully.

**Comment by MuhammadAbuBakar95** [comment]
Thanks for letting me know.

**Comment by shiheyuan** [comment]
> Hi,
> 
> Thanks a lot for providing such a useful tool.
> I am trying to generate a fine-grained call graph for a (large) kernel. For this problem, I am using SVF to generate points-to sets for pointer operands of indirect call Instructions. I have used the Diff wave propagation inclusion-based analysis.
> After going through the results, one issue that I see is that for 900 of these call sites, the target set is exactly the same and contains more than 6500 functions (which is one third of the total number of functions in my IR). Most of these functions seem completely unrelated to the call sites.
> 
> Can you help me in figuring out what is going on?
> Is it possible that you guys are using a conservative approach (e.g. signature matching) to overestimate the points-to set that is leading to this result?
> 
> Thanks.

@MuhammadAbuBakar95 
Could you teach me how to generate the callgraph for the kernel? 
How to generate bitcode of Linux kernel properly and use the wpa in your way?
I have tried to generate vmlinux.bc by wllvm and clang, but I meet the errors like below:

```
wpa: home/SVF/include/MemoryModel/MemModel.h:571: SymID SymbolTableInfo::getValSym(const Value*): Assertion `iter!=valSymMap.end() &&"value sym not found"' failed.
```

Thanks.
