### ISSUE TITLE
Unsoundness for address-taken external functions allocating memory

### ISSUE THREAD

**Issue by taptipalit** [SVF-tools/SVF#172]
Analysis breaks when the address of an external function, that allocates and returns an object on the heap, is stored to a function pointer, and later dereferenced at an indirect call-site.

Reduced test case is attached in test.c.txt

I'm running with  -ander -dump-callgraph, with the latest commit on master.

Expected behavior: I expect the analysis to find the indirect call-edges from dothis() -> f() and dothat-> g(). 

Observed behavior: Analysis fails to find the above indirect call-edges.

Additional Comments: 
I identified two places of concern: 
1. PAGBuilder.cpp does not collect PAG return nodes for external functions (line 61). But in ConsG.cpp, in connectCaller2CalleeParam(), the connecting of return values is done only when the function (malloc, in this case) has a PAG return node.
2. PAGBuilder.cpp models external functions such as malloc, as EFT_ALLOC and adds an ObjectNode for the call-sites (line 741). I think something similar should be done, when the on-the-fly-call-graph solving resolves an indirect call-site to point to an external function of EFT_ALLOC type. I might have missed it, but I couldn't find this case being handled during on-the-fly-call-graph solving.

In libssl/libcrypto libraries, CRYPTO_malloc(), which is used to allocate memory accesses malloc through a function pointer.

[test.c.txt](https://github.com/SVF-tools/SVF/files/4094588/test.c.txt)

**Comment by yuleisui** [comment]
Hello taptipalit,

Thanks for reporting this unsoundness. We were aware of this.  We plan to allow all external functions to have their return nodes (`funRetMap`) and also their formal args (`funArgsListMap'). Each external function will have its own an artifact subPAG based on function summary (`ExternalAPI`). The subPAG will be connected to the main PAG during resolution. This is still undergoing. It may take some time for us to refactor the code to make the minimum changes so that SVF users would not affect much.

For now, I have just updated SVF with a new patch to support the case when an indirect call is resolved to be a heap allocator. This will solve the problem of your program.

2e5e41b5b62584f7dafc11905451d0d28d639cd7

**Comment by taptipalit** [comment]
Thanks for the very prompt response and fix. 

Confirmed that the patch works for my case.
