### ISSUE TITLE
SVFG lacks def-use information of nested structure 

### ISSUE THREAD

**Issue by Y-chav** [SVF-tools/SVF#340]
`#include <stdlib.h>

struct inner
{
        char *three;
        char *four;
};

struct outer
{
        char *one;
        char *two;
        struct inner* gg;
};

void test(struct outer *b)
{
        b->gg->three = malloc(0x30);
        free(b->gg->three);
}`

![image](https://user-images.githubusercontent.com/44321769/96676872-f3264a00-13a0-11eb-9859-a1a903e80c70.png)

It should be an Indirect edge between Node15 and Node16, but it doesn't.

**Comment by yuleisui** [comment]
`free` is not treated as a use site in the original SVFG. You can use saber's one to dump the SVFG for your purposes. `saber -dump-svfg xxx.bc`

**Comment by Y-chav** [comment]
I don't think it‘s because of **free**. I change free into load, the same problem exists.

`struct inner
{
    char *three;
    char *four;
};

struct outer
{
    char *one;
    char *two;
    struct inner* gg; 
};

void test(struct outer *b) 
{
    b->gg->three = (int*)malloc(0x30);
    int c = *(b->gg->three);
}`

![image](https://user-images.githubusercontent.com/44321769/96677799-eb67a500-13a2-11eb-9c81-451fc3ea3c66.png)

The edge between Node17 and Node19 is missing.

**Comment by yuleisui** [comment]
@mbarbar would you mind taking a look at this SVFG?

**Comment by mbarbar** [comment]
`b` points to nothing (@yuleisui does SVF put dummies in place for arguments of uncalled functions?). Otherwise, assuming `b` points to something, `gg` points to nothing (it is uninitialised), so you can't reach `three` to assign something to it. The lack of edge starts at memory SSA construction, because the relevant points-to sets are empty in the Andersen's results.

If you initialise `b` and initialise `gg`, or declare it as `struct inner gg`, the edge should exist I believe.

**Comment by yuleisui** [comment]
@mbarbar correct, `b` points to nothing. @Y-chav can you call `test` in another method with a proper argument?

**Comment by Y-chav** [comment]
Thanks a lot, I do as you said, this time the edge exists.

**Comment by mbarbar** [comment]
Good to hear!
