### ISSUE TITLE
Does SVF change the module it analyses? 

### ISSUE THREAD

**Issue by kren1** [SVF-tools/SVF#39]
Hi,

I observed that after running a pointer analysis (AnderesenWaveDiff), the number of instructions in an LLVM module increases. From what I gather the analsysis itself, never changes the module it analyses. Is that true or did I miss something? Another thing I was considering is that SVF registers itself as an LLVM alias analysis and then another transformation uses it's more precise results to emit different code. However I'm not running any other pass after the SVF analysis. Any other ideas?

**Comment by yuleisui** [comment]
Hello,

1) On bc file changes
SVF may break constantExpr into an instruction and create a dummy return by merging multiple return instructions.

Please see "Util/BreakConstantExpr.h"

The best way to see the changes is to diff the two bc files (before and after SVF's analyses).

2) Alias analysis registration

The current version of SVF does not register itself as an LLVM alias analysis since LLVM moves very fast and its orignal registration interfaces have changed few times.  If you possible, would you like to help us with this?

**Comment by kren1** [comment]
Hi,

Thanks for clarifying why the changes happen, it has been bugging me for a while.

I don't have any experience with registering those passes especially not across llvm version and I usually work in llvm 3.4, so I don't think I would be of much help.

Thanks again for your quick response and I'm sorry I can't be of more use on this.

**Comment by yuleisui** [comment]
No worries. Good luck!
