### ISSUE TITLE
Aborted in cudddTable.c:343

### ISSUE THREAD

**Issue by macromachine** [SVF-tools/SVF#46]
Hello,
After I have installed SVF as https://github.com/SVF-tools/SVF/wiki/Setup-Guide-(CMake),
I run the example in https://github.com/SVF-tools/SVF/wiki/Analyze-a-Simple-C-Program .

When we run wpa -ander -svfg swap.bc,
the program outputs some information, but at last it reported the abort as follows:
wpa: $SVF_Home/lib/CUDD/cuddTable.c:343: cuddAllocNode: Assertion `((ptruint) mem & (sizeof(DdNode) - 1)) == 0' failed.

How to solve this problem? thanks

**Comment by yuleisui** [comment]
Hello,

It seems to me that this error is caused by an integer overflow in CUDD.

Did you compile correctly the CUDD code with the correct options (see https://github.com/SVF-tools/SVF/blob/master/lib/CUDD/CMakeLists.txt) on a 64-bit machine using a correct compiler (one can recognize the options)?

In fact, only Saber uses CUDD, but pointer analyses in SVF do not. You can also remove the dependence by simply working around assertion for building SVFG.

**Comment by macromachine** [comment]
Thanks for reply.
I compile SVF on 32-bit machine.

**Comment by yuleisui** [comment]
Then try it on 64-bit one ...

**Comment by macromachine** [comment]
I have tried it today,  and it passes.
If I want use it on 32-bit machine, how should I do?

Besides, I have another question.
How to understand the SVFG?
For example, NodeID:10  2<--3, 
what is nodeid, how to correspond to the source code line?
what do they mean 2 and 3?
