### ISSUE TITLE
Query regarding must aliases

### ISSUE THREAD

**Issue by anilavakundu** [SVF-tools/SVF#517]
I am trying to use the flow-sensitive alias analysis (read wpa -fspta) but it seems that the alias function manages to only show may alias as of now (which can also be seen here: https://github.com/SVF-tools/SVF/blob/18d6c31127f7ea8a6f45d001ed389326cc2a3f28/lib/WPA/WPAPass.cpp#L200).

Having said this the test-suite (https://github.com/SVF-tools/Test-Suite) contains flow-sensitive tests with MustAlias checks in them (read: https://github.com/SVF-tools/Test-Suite/blob/679209ca96f584cd9ceaad5ea5c45c53186d8a02/src/fs_tests/simple_1.c#L16) 

I have looked into the points to sets for these pointers which are singletons which makes sense but can all pointers having similar singleton sets be classified as MustAlias or was this annotated manually and classifying all such pointers as must alias would be wrong?

I am pretty new to this any help would be greatly appreciated! Thanks!

**Comment by mbarbar** [comment]
It would be incorrect to apply it everywhere.

```
1: int *p;
2: if (...) p = &x;
3: if (...) q = &x;
4: ...
```

`pt(p)` and `pt(q)` at line 4 would both be `{ x }` but you can't say they must-alias since either or both could be uninitialised. (That said, if the alias test was at a dereferencing of the pointers -- where aliasing is probably more useful -- it would be illegal for either of them to be uninitialised and the program would be undefined. If the program is not undefined, they both must point to `x`.)

**Comment by anilavakundu** [comment]
@mbarbar Thanks for the reply! this makes sense. From what I understand this case (read: Undef) is handled by black hole nodes in the PAG which also handles cases where it is statically not possible to determine where a pointer points. 

That being said, in the condition here: https://github.com/SVF-tools/SVF/blob/18d6c31127f7ea8a6f45d001ed389326cc2a3f28/lib/MemoryModel/PointerAnalysisImpl.cpp#L430

is it safe to assume/add a condition that two pointers would MustAlias if they have similar points to set (Singletons) and don't contain blackhole nodes?
