### ISSUE TITLE
Instructions reachable from function arguments

### ISSUE THREAD

**Issue by anahitH** [SVF-tools/SVF#68]
Hello,

I want to use PAG and SVFG graphs to collect instructions reachability information. Particularly for every function I need to find instructions reachable by each of function arguments. Do I understand it correctly that first I’ll need to extend PAG to include all the instructions as now PAGBuilder doesn’t process all types of instructions. Then traverse extended PAG to find instructions reachable from function arguments. Will PAG reflect aliasing information for pointers, or do I need to use SVFG for it?

Thanks!

**Comment by yuleisui** [comment]
Hi Anahit,

SVF's PAG/SVFG now only includes pointer related instructions since scalars' def-use information are explicit on LLVM's SSA. It may wish to directly query the LLVM IR for def-use if you want scalars' value-flows

SVFG reflects aliasing information for traversing on the Graph for program dependence. 

See the issue: https://github.com/SVF-tools/SVF/issues/45
See Wiki: https://github.com/SVF-tools/SVF/wiki/Write-a-source-sink-analyzer

**Comment by anahitH** [comment]
Thank you!!
