### ISSUE TITLE
Is SVFG flow-sensitive?

### ISSUE THREAD

**Issue by Machiry** [SVF-tools/SVF#75]
First question: Is SVFG flow-sensitive? It uses memory SSA but doesn't respect the control-flow.  
For example: If a `store` and `load` define and use the same region, they will be connected **irrespective** of whether there is a path from the store to load in the CFG.

If SVFG is not flow-sensitive, How is the `FlowSensitive` pointer analysis (type: `FSSPARSE_WPA`) flow sensitive? As it solves the constraints over the SVFG.

**Comment by yuleisui** [comment]
1) Short answer, Yes. SVFG is constructed using Memory SSA which respects control-flows (MemSSA is flow-sensitive). See https://github.com/SVF-tools/SVF/blob/b7ddf981ae1e3be79eab691f6cf844313ee66b77/lib/MSSA/MemSSA.cpp#L108  
For your example, `store` will flow to `load` following the control-flow. However the memory regions can be created using the points-to information from any pointer analysis. The default SVFG is built via `wpa -ander -svfg xx.bc`, which uses flow-insensitive Andersen's results.

2) SVFG is flow-sensitive, but pointer analysis used may be insensitive, which means that there can be spurious value-flows due to imprecise aliasing. `FSSPARSE_WPA` operates on top of the default SVFG to produce flow-sensitive pointer analysis results. Note that SVF supports iteratively SVFG contruction. If you feed `FSSPARSE_WPA` into MemSSA, it will build a new, say SVFG+, which is more precise than the original SVFG since the memory regions are refined.

**Comment by Machiry** [comment]
This may sound dumb, but what happens when I iteratively feed `FSSPARSE_WPA` to `MemSSA` which gives me improved SVFG and again feed the improved SVFG to `FSSPARSE_WPA`.

Does the precision reach a fixed point? or this is completely pointless and I am missing something trivial?

**Comment by yuleisui** [comment]
The SVFG can be used for different client applications and pointer analysis is one of them.

PTA1 -> SVFG1 -> PTA2 -> SVFG2 -> PTA3 -> SVFG3

Normally the PTAs should be different and gradually more precise. Therefore, after the second iteration, you may only wish to use more precise pointer analysis (e.g., context-sensitive one) to further improve the precision. Keep using the flow-sensitive pointer analysis will not improve the precision since spurious value-flows (caused by insensitive points-to info) have already been eliminated. 

Note that there is no free lunch. When applying a more heavy-weight pointer analysis, the analysis time will increase significantly and the benefit may be small. The first iteration (e.g., default one) is a good trade-off for many clients.

**Comment by Machiry** [comment]
Make sense. Thank You.
