### ISSUE TITLE
Multiple NodeIDs for a single instruction?

### ISSUE THREAD

**Issue by Machiry** [SVF-tools/SVF#77]
I am looking at a PAG, where 2 **different** NodeIDs map to the same Value*.
I have never seen this case. Can this happen?

**Comment by yuleisui** [comment]
If the LLVM value is a memory allocation (e.g., LLVM's global `@xx`, heap or stack allocations), two nodes will be created. One represents the abstract object (ObjPN) and another is the pointer (ValPN) points to this object.

**Comment by Machiry** [comment]
Actually, it's a load instruction and both the nodes are ValPN

**Comment by yuleisui** [comment]
Can you print the `load` instruction?

**Comment by Machiry** [comment]
```
%665 = load i8*, i8** %origfilename.i, align 8, !dbg !4780, !tbaa !4749
```

**Comment by yuleisui** [comment]
If this an instruction (not a consexpr), `MemoryModel` can only create a unique PAGNode ID for `%665`.

Please find the call stack below for creating the node and its ID in `symTyMap` map.

https://github.com/SVF-tools/SVF/blob/b7ddf981ae1e3be79eab691f6cf844313ee66b77/lib/MemoryModel/MemModel.cpp#L666

==>

https://github.com/SVF-tools/SVF/blob/b7ddf981ae1e3be79eab691f6cf844313ee66b77/lib/MemoryModel/MemModel.cpp#L758

==>

https://github.com/SVF-tools/SVF/blob/b7ddf981ae1e3be79eab691f6cf844313ee66b77/lib/MemoryModel/MemModel.cpp#L769

For the same instruction `%665 = load i8*, i8** %origfilename.i`, we should only enter`collectVal` once. Could you please provide me with the scenario of the second entrance to `collectVal` using the same `load` instruction by using a conditional debugging it? 

Another possibility is that the new ID might be created somewhere else if the bc code was changed.

**Comment by Machiry** [comment]
There are 2 PAGNodes, one is regular PAGNode and another one is: `GepValNode`. 

According to the code:

https://github.com/SVF-tools/SVF/blob/b7ddf981ae1e3be79eab691f6cf844313ee66b77/lib/MemoryModel/PAG.cpp#L231

```
/*!
 * Add a temp field value node according to base value and offset
 * this node is after the initial node method, it is out of scope of symInfo table
 */
NodeID PAG::getGepValNode(const llvm::Value* val, const LocationSet& ls, const Type *baseType, u32_t fieldidx) {
```
I think PAG adds a dummy GEP node to be `field sensitive` and uses the original `Value*`.

```
%origfilename.i = getelementptr inbounds %struct.httpd_conn, %struct.httpd_conn* %370, i64 0, i32 15, !dbg !4743
%436 = load i8*, i8** %origfilename.i, align 8, !dbg !4780, !tbaa !4749
```

Given that our load instruction is as shown above. I believe this is the case.

Let me know if this is the correct?

**Comment by yuleisui** [comment]
If the other node is a `GepValNode`, I think this is a correct.

`GepValNode` is a dummy node created for special purposes as explained in `getGepValNode `
In your example, I guess "curVal" (current instruction) is an external function call
https://github.com/SVF-tools/SVF/blob/f6d9758675e6bb31e61e13c33503ab90242fcb25/lib/MemoryModel/PAG.cpp#L243

Based on your description, the external call might be doing a deep copy for fields of an struct object (e.g.,  `memcpy(%436, %target)`). In this case, the code of the external function is incomplete. Therefore, we need to model the side-effects by creating a dummy value node say `tmp` to represent a field reference to a field of the object that %436 points to. 

When referencing code
https://github.com/SVF-tools/SVF/blob/9b5c5403c241fb35566797eb316d2dddeb37c93b/lib/MemoryModel/PAGBuilder.cpp#L705

 `tmp` mentioned is `sField `.  `%436` is `S`. The load and store edges are performing deep copy for  `index`-th field.

We put `%436` (the argument of the external call) as the LLVM value when creating a `GepValNode `. Actually, the LLVM value here is just a placeholder since the code of the external call is incomplete and we can't get the value here for our deep copy modeling. Puting a "null" also may not be a good choice.

**Comment by Machiry** [comment]
Thank You for the explanation.
