### ISSUE TITLE
Path-sensitive points-to analysis?

### ISSUE THREAD

**Issue by rainoftime** [SVF-tools/SVF#78]
In `MemoryModel/PointerAnalysis.h`,  there are several path-sensitive points-to analyses. 
Are they implemented in current version? If so, does SVF provide command-line interface for choosing them? Thank you!
~~~~
    /// Pointer analysis type list
    enum PTATY {
       // ...
        FSCSPS_WPA,		///< Flow-, context-, path- sensitive WPA
        ADAPTFSCS_WPA,		///< Adaptive Flow-, context-, sensitive WPA
        ADAPTFSCSPS_WPA,	///< Adaptive Flow-, context-, path- sensitive WPA
       //..
    };
~~~~

**Comment by yuleisui** [comment]
Unfortunately, these are not available now in SVF. We may release a flow- and context-sensitive analysis based on our FSE '16 paper later this year.

**Comment by danilaml** [comment]
Thanks for the tool! It's hard to find anything like this available. I really hope to see CS analysis, since I didn't find any readily available (and especially for modern LLVM version).

I was also confused with PTATY enum and the list of available analysis. Perhaps it'd be beneficial to document the current publicly supported analyses somewhere visible.
