### ISSUE TITLE
Can IntraDirSVFGEdge having srcNode and dstNode from different functions?

### ISSUE THREAD

**Issue by Machiry** [SVF-tools/SVF#83]
Hi @yuleisui,

I am facing an issue where an `IntraDirSVFGEdge` has the src node (`getSrcNode` ) and dst node (`getDstNode` ) belong to **different functions**. 

However, by definition *Intra* edges should only connect nodes that belong to the same function.

Can this happen? If yes, could you please describe what does this mean? Why do we need to make it an IntraDir edge?

**Comment by yuleisui** [comment]
Did this happen when you were using SVFGOPT or SVFG?

Can you provide more information such as what are the types of the two nodes and their corresponding LLVM values?

**Comment by yuleisui** [comment]
May I know the types of "Src:SVFGNode" and "Dst:SVFGNode" and also the types of two Pag eges?

**Comment by Machiry** [comment]
Src:
`GepSVFGNode`
Src Pag Edge:
 `NormalGEPPE`

Dst: 
`StoreSVFGNode`
Dst Pag Edge:
 `StorePE`

**Comment by yuleisui** [comment]
I still don't have a clue for this. Is the bc file very large for debugging? Could you please check the following?
1) Did you get the two functions through `PAGEdge->getBB()->getParent()`? If so please check whether the basicblocks/funcitons were associated with the PAGEdges correctly?
https://github.com/SVF-tools/SVF/blob/ee23492712f8ca1de1d879f873e9a5ad61f5fdff/lib/MemoryModel/PAG.cpp#L361

2) Was the IntraDirSVFEdge created during SVFG construction or during SVFG Optimisation?
https://github.com/SVF-tools/SVF/blob/ee23492712f8ca1de1d879f873e9a5ad61f5fdff/lib/MSSA/SVFG.cpp#L281

I can help with some debugging using your bc If you really can't find the reason.

**Comment by Machiry** [comment]
I found the root cause:

In https://github.com/SVF-tools/SVF/blob/ee23492712f8ca1de1d879f873e9a5ad61f5fdff/lib/MSSA/SVFG.cpp#L287

```
if(const StmtSVFGNode* stmtNode = dyn_cast<StmtSVFGNode>(node)) {
            if(isa<AddrSVFGNode>(stmtNode))
                continue;
            addIntraDirectVFEdge(getDef(stmtNode->getPAGSrcNode()),nodeId);

           
            if(isa<StoreSVFGNode>(stmtNode)) {
              // HERE: getDef gets the SVFG node that belongs to different function and we end up adding Intra edge rather than Inter
                addIntraDirectVFEdge(getDef(stmtNode->getPAGDstNode()),nodeId);
            }

        }
```

If the `getDef(stmtNode->getPAGDstNode())` belongs to different function, shouldn't we add `IndirectSVFGEdge`? I am not sure, if this is the correct fix.

To reproduce this isse:

Add this:
```
if(srcNode->getBB() != nullptr && dstNode->getBB() != nullptr) {
        assert(srcNode->getBB()->getParent() == dstNode->getBB()->getParent());
    }
```
Before this line: https://github.com/SVF-tools/SVF/blob/ee23492712f8ca1de1d879f873e9a5ad61f5fdff/lib/MSSA/SVFG.cpp#L541

**Comment by yuleisui** [comment]
Unfortunately, this is not the root cause.

Since our memory SSA form is parameterised, `getDef()` can only get the intra-procedural definition. Connecting interprocedural edges are done via

https://github.com/SVF-tools/SVF/blob/3038078e90eb037ea43aa28ff3a28c05d631be5d/include/MSSA/SVFG.h#L303-L315

'stmtNode' (_StoreSVFGNode_) and `getDef(stmtNode->getPAGDstNode())` (_GepSVFGNode_) should be in the same function.

Let me try your bc file to have a look.

**Comment by yuleisui** [comment]
I have just committed a patch https://github.com/SVF-tools/SVF/commit/ee23492712f8ca1de1d879f873e9a5ad61f5fdff  to fix this issue 

It is a bit complicated to explain the fix. Remember that we were discussing about `GepValNode` at https://github.com/SVF-tools/SVF/issues/77.

The reason is that we didn't create a unique `GepValNode` at every external callsite to handle complex constraints https://github.com/SVF-tools/SVF/blob/9b5c5403c241fb35566797eb316d2dddeb37c93b/lib/MemoryModel/PAGBuilder.cpp#L679

Let us revisit the full info below for the two SVFGNodes. Note that the `dstNode` SVFGNode you gave me is wrong. **The Dst PAGNode of the _StorePE_ is not a dummy node but is `%10` which is the same as Dst PAGNode of the _GepPE_.** In fact, they should be different since they reside in different functions. 

The reason is that when analysing the callsite `llvm.memcpy` in `main` function, we failed to create a new `GepValNode`, but kept reusing the old one which was created in `invite_remote` function.

```
srcNode: SVFGNode ID:862

Function Name: invite_remote

Src PagNode Value: 
@msg = internal dso_local global %struct.CTL_MSG zeroinitializer, align 8, !dbg !69 

Dst PagNode Value:
%10 = getelementptr %struct.CTL_MSG, %struct.CTL_MSG* @msg, i64 0, i32 5, i32 1, i64 0

Pag Edge Value:
call void @llvm.memcpy.p0i8.p0i8.i64(i8* %10, i8* %12, i64 14, i32 2, i1 false), !dbg !1138


dstNode:SVFGNode ID: 3244

Function Name: main

Src PagNode value: Dummy Node
Dst PagNode value: %10 = getelementptr %struct.CTL_MSG, %struct.CTL_MSG* @msg, i64 0, i32 5, i32 1, i64 0


Pag Edge Value:
call void @llvm.memcpy.p0i8.p0i8.i64(i8* %107, i8* %109, i64 14, i32 2, i1 false) #8, !dbg !1647
```

It feels good that we have fixed this. Thanks for pointing this out.

**Comment by yuleisui** [comment]
Just want to add one more point. The previous version before the patch is correct for flow-insensitive analysis, but `GepValNode` does not have the correct instruction/basicblock info for flow-sensitivity.

**Comment by Machiry** [comment]
Looks like the fix is not complete. Attached is another bc file, which is affected by the same issue.
[ftp.0.4.opt.mem2reg.bc.zip](https://github.com/SVF-tools/SVF/files/2279592/ftp.0.4.opt.mem2reg.bc.zip)

**Comment by yuleisui** [comment]
Fixed by https://github.com/SVF-tools/SVF/commit/28ee1453f0182f4fa932aeb0a0d6448d3eba9772.

Let me know if the `GepValNode` is still not flow-sensitive when testing more benchmarks.

**Comment by Machiry** [comment]
Looks like this is resolved now. Thank You @yuleisui
