### ISSUE TITLE
Can I run multiple instances of the same Pointer analysis in a single run?

### ISSUE THREAD

**Issue by Machiry** [SVF-tools/SVF#86]
Hi @yuleisui,

I was trying to run multiple instances of same pointer analysis on the same `svfModule` in a single program. 

I am seeing some inconsistencies w.r.t to field sensitivity of certain objects.
Before trying to debug, I want to know if this is supported or there is certain mutable global state maintained that could affect multiple instances of the same pointer analysis?

**Comment by yuleisui** [comment]
I don't think it is possible at this stage since we have a unique PAG and the new (gep) nodes are created and added to the unique PAG. It may cause data-races when running two Andersen's analysis simultaneously. It is ok to do one pointer analysis after another, e.g., flow-sensitive after Andersen.

May I know why did you want to run multiple instances of the same pointer analysis? Parallel pointer analysis?

**Comment by Machiry** [comment]
Not in parallel but one after the other.

Like the following:
```
FlowSensitive *fp1 = new FlowSensitive();
fp1->analyze(svfm);

FlowSensitive *fp2 = new FlowSensitive():
fp2->analyze(svfm);
```
Can I expect the results of both `fp1` and `fp2` to be same?

**Comment by yuleisui** [comment]
It seems ok to me..

**Comment by yuleisui** [comment]
We didn't test this since one pointer analysis is assumed to be resolved only once.

**Comment by yuleisui** [comment]
It might be ok if you do `finalize()` after every pointer analysis (i.e., `pta->analyze()`) since we have `https://github.com/SVF-tools/SVF/blob/9b5c5403c241fb35566797eb316d2dddeb37c93b/lib/MemoryModel/PointerAnalysis.cpp#L196` for resetting field-sensitivity.

**Comment by Machiry** [comment]
Thank You.
I also need a few other things to be preserved. To be on the safe side, I would rather run the analysis twice in 2 different processes :)

**Comment by ShimchenkoMarina** [comment]
Hello, 
this is exactly what I need to do. The difference is that I use AndersenWaveDiff: 
AndersenWaveDiffWithType* svfResults;
svfResults = AndersenWaveDiffWithType::createAndersenWaveDiffWithType(module);
.....
svfResults->releaseAndersenWaveDiff();
svfResults = AndersenWaveDiffWithType::createAndersenWaveDiffWithType(module);

I release it because I change the module and I want to recalculate this analysis. However, I get an error:
llvm::Value::assertModuleIsMaterialized() const + 24
llvm::Function::hasAddressTaken(llvm::User const**) const + 28
analysisUtil::isDeadFunction(llvm::Function const*) + 32
analysisUtil::isNoCallerFunction(llvm::Function const*) + 24
analysisUtil::ArgInNoCallerFunction(llvm::Value const*) + 56 
PAG::isValidTopLevelPtr(PAGNode const*) + 116

I am not quite sure what it means that a module is materialized. Do you have ideas about why I might run into such a problem?

**Comment by mbarbar** [comment]
To me the errors sound like sanity checks on the module. I'm unsure, but it sounds like the source of error is the change you make to the module, not that you analysed twice. You can verify this by trying changes->analysis1 instead of analysis1->changes->analysis2. What sort of changes are you making to the module by the way?

This answer seems to provide a little info on materialization that might be useful: https://stackoverflow.com/questions/45642228/what-does-materialize-mean-in-llvm-globalvalue-h
