### ISSUE TITLE
Some questions related to the CFL Graph building

### ISSUE THREAD

**Issue by enochii** [SVF-tools/SVF#922]
Hello, thanks for the great work!

I have some doubts about the CFL graph building. In `CFLBase::buildCFLGraph`, if the `Options::CFLGraph` is not provided, `SVF` will build the CFL Graph from `ConstraintGraph`. Since `ConstraintGraph` is context insensitive, i.e. treats call/ret edges as copy edge(see `ConstraintGraph::buildCG()`), CFL problems with context sensitivity are not supported right now? (I saw a `VFG.txt` grammar is provided in `include/CFL` directory.)

Also, I wonder what `AliasCFLGraphBuilder::buildBigraph` does. In the following code snippet, the edge label of `ConstraintEdge` are directly assigned to a local var with type `CFLGrammar::Kind`, it seems inconsistent with `AliasCFLGraphBuilder::buildBiPEGgraph`. Is it correct?

```c++
...
for(auto it = graph->begin(); it!= graph->end(); it++)
    {
        ConstraintNode* node = (*it).second;
        for(ConstraintEdge* edge : node->getOutEdges())
        {
            CFLGrammar::Kind edgeLabel = edge->getEdgeKind();
            // ...
        }
    }
...
```

**Comment by yuleisui** [comment]
@TalbenXu could you help answer this question?

**Comment by TalbenXu** [comment]
Hi, how are you enochii?  Thank you for the comments and suggestions.

1. If the Options::CFLGraph is not provided then CFLGraph will builded from bc e.g(those .bc file in test suite). And the Constrant Graph does not contains the return and call callsite information so that one is context-insensitive. So the client Alias PEG or PAG here is context insensitive. Here is just field sensitive.

2. Value Flow Analysis's CFLGraph is comming from SVFG, in this case, SVFG is contains the callsite informaiton so is context sensitive. (as grammar A ->call_i A ret_i ).

3. If Alias analysis wants to be context sensitive, it needs to add additional context information to edge offset when building CFLGraph and also add the match process production to CFL Grammar.(it should be not hard to achieve on top of existed client)

4. When CFLGraph builded from AliasCFLGraphBuilder::buildBiPEGgraph, then the store and load complex statement will transfer to copy and addr edge in the process. Other part should be same meaning with AliasCFLGraphBuilder::buildBigraph.

Regards
Pei

**Comment by TalbenXu** [comment]
Hi, enochii. Thank you for the comments.

Yes, since CFLGraph is blind with "text symbol" only have num representation, the source graph needs to align with the grammar order in text file.

Regards
Pei

**Comment by enochii** [comment]
Hi, Pei.

Got it, Thanks for your explanation again! Have a nice day~
